// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities
{
    [Table("Course")]
    public partial class Course
    {
        public Course()
        {
            Exams = new HashSet<Exam>();
            Questions = new HashSet<Question>();
            StudCourses = new HashSet<StudCourse>();
            Topics = new HashSet<Topic>();
            Insts = new HashSet<Instructor>();
        }

        [Key]
        [Column("course_id")]
        public int CourseId { get; set; }
        [Column("course_name")]
        [StringLength(20)]
        public string CourseName { get; set; }

        [InverseProperty(nameof(Exam.Course))]
        public virtual ICollection<Exam> Exams { get; set; }
        [InverseProperty(nameof(Question.Course))]
        public virtual ICollection<Question> Questions { get; set; }
        [InverseProperty(nameof(StudCourse.Course))]
        public virtual ICollection<StudCourse> StudCourses { get; set; }
        [InverseProperty(nameof(Topic.Course))]
        public virtual ICollection<Topic> Topics { get; set; }

        [ForeignKey("CourseId")]
        [InverseProperty(nameof(Instructor.Courses))]
        public virtual ICollection<Instructor> Insts { get; set; }
    }
}