// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities
{
    [Table("Department")]
    public partial class Department
    {
        public Department()
        {
            Instructors = new HashSet<Instructor>();
            Students = new HashSet<Student>();
        }

        [Key]
        [Column("dept_id")]
        public int DeptId { get; set; }
        [Column("dept_name")]
        [StringLength(50)]
        public string DeptName { get; set; }

        [InverseProperty(nameof(Instructor.Dept))]
        public virtual ICollection<Instructor> Instructors { get; set; }
        [InverseProperty(nameof(Student.Dept))]
        public virtual ICollection<Student> Students { get; set; }
    }
}