// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class displayAllStudentInfo_DeptidResult
    {
        public int std_id { get; set; }
        public string f_name { get; set; }
        public string l_name { get; set; }
        public int dept_id { get; set; }
        public string dept_name { get; set; }
    }
}
