// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities
{
    [Table("Exam_choices")]
    public partial class ExamChoice
    {
        [Key]
        [Column("Q_id")]
        public int QId { get; set; }
        [Key]
        [Column("choices")]
        [StringLength(100)]
        public string Choices { get; set; }

        [ForeignKey(nameof(QId))]
        [InverseProperty(nameof(Question.ExamChoices))]
        public virtual Question QIdNavigation { get; set; }
    }
}