// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class examAnswersResult
    {
        public string Question { get; set; }
        public string std_answer { get; set; }
        public string Q_model_answer { get; set; }
    }
}
