// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class get_instResult
    {
        public int inst_id { get; set; }
        public string inst_name { get; set; }
        public int dept_id { get; set; }
    }
}
