// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class get_all_topicsResult
    {
        public int topic_id { get; set; }
        public string topic_name { get; set; }
        public int course_id { get; set; }
    }
}
