// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace ExaminationSystem.Entities
{
    public partial class gradesStudentAllCoursesResult
    {
        public string course_name { get; set; }
        public int? course_grade { get; set; }
    }
}
