// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities
{
    [Table("Q_ex_stud")]
    public partial class QExStud
    {
        [Key]
        [Column("Q_id")]
        public int QId { get; set; }
        [Key]
        [Column("ex_id")]
        public int ExId { get; set; }
        [Column("stud_id")]
        public int? StudId { get; set; }
        [Column("std_answer")]
        [StringLength(20)]
        public string StdAnswer { get; set; }

        [ForeignKey(nameof(ExId))]
        [InverseProperty(nameof(Exam.QExStuds))]
        public virtual Exam Ex { get; set; }
        [ForeignKey(nameof(QId))]
        [InverseProperty(nameof(Question.QExStuds))]
        public virtual Question QIdNavigation { get; set; }
        [ForeignKey(nameof(StudId))]
        [InverseProperty(nameof(Student.QExStuds))]
        public virtual Student Stud { get; set; }
    }
}