// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities
{
    [Table("Student")]
    public partial class Student
    {
        public Student()
        {
            QExStuds = new HashSet<QExStud>();
            StudCourses = new HashSet<StudCourse>();
        }

        [Key]
        [Column("std_id")]
        public int StdId { get; set; }
        [Column("f_name")]
        [StringLength(20)]
        public string FName { get; set; }
        [Column("l_name")]
        [StringLength(20)]
        public string LName { get; set; }
        [Column("dept_id")]
        public int DeptId { get; set; }

        [ForeignKey(nameof(DeptId))]
        [InverseProperty(nameof(Department.Students))]
        public virtual Department Dept { get; set; }
        [InverseProperty(nameof(QExStud.Stud))]
        public virtual ICollection<QExStud> QExStuds { get; set; }
        [InverseProperty(nameof(StudCourse.Stud))]
        public virtual ICollection<StudCourse> StudCourses { get; set; }
    }
}