// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities
{
    [Table("Stud_course")]
    public partial class StudCourse
    {
        [Key]
        [Column("course_id")]
        public int CourseId { get; set; }
        [Key]
        [Column("stud_id")]
        public int StudId { get; set; }
        [Column("course_grade")]
        public int? CourseGrade { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("StudCourses")]
        public virtual Course Course { get; set; }
        [ForeignKey(nameof(StudId))]
        [InverseProperty(nameof(Student.StudCourses))]
        public virtual Student Stud { get; set; }
    }
}