// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ExaminationSystem.Entities
{
    [Table("Topic")]
    public partial class Topic
    {
        [Key]
        [Column("topic_id")]
        public int TopicId { get; set; }
        [Column("topic_name")]
        [StringLength(50)]
        public string TopicName { get; set; }
        [Column("course_id")]
        public int CourseId { get; set; }

        [ForeignKey(nameof(CourseId))]
        [InverseProperty("Topics")]
        public virtual Course Course { get; set; }
    }
}